### ISSUE TITLE
last_insert_id와 관련해서 궁금한것이 있습니다

### ISSUE THREAD

**Issue by siyoon210** [yjs2952/slowcampus#3]
https://github.com/yjs2952/slowcampus/blob/2a4d1d60daa8fc1784cb9d69550b5809d647ed9b/src/main/java/com/slowcampus/dao/BoardDaoImpl.java#L74

이런식으로 last_insert_id 불러올때
마지막으로 insert 구문을 처리한 테이블이 board가 아니라 다른테이블(예를들어 member)테이블인 경우도 정상적으로 board의 last_insert_id를 가져오나요?

제가 샘플sql로 해볼땐 마지막으로 사용된 테이블의 last_insert_id를 가져왔던것 같아서요

**Comment by yjs2952** [comment]
저희 프로젝트에 관심 가져주셔서 감사합니다. 
문의 해 주신 내용은 테스트 후 알려드리겠습니다.
